name: Build Linux arm64 standalone otp-release

on: 
  workflow_dispatch:
    inputs:
      otp-release-version:
        required: true
        description: 'The git revison of OTP release to use'     
        default: 'OTP-27.1.2'
      openssl-version:
        required: true
        description: 'The git revison of OpenSSL to use'
        default: "openssl-3.4.0"

jobs:
  build-standalone-linux-arm64-otp-release:
    runs-on: [self-hosted, Linux, ARM64, ubuntu-latest-arm64]
    steps:
      -
        name: Checkout Repo
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GAO_OS_SSH_KEY }}
          ref: main
      -
        name: Checkout otp
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GAO_OS_SSH_KEY }}
          repository: erlang/otp
          ref: ${{ github.event.inputs.otp-release-version }}
          path: otp
      -
        name: Checkout openssl
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.GAO_OS_SSH_KEY }}
          repository: openssl/openssl
          ref: ${{ github.event.inputs.openssl-version }}
          path: openssl
      -
        name: Setup build environment
        run: |
          sudo apt update
          sudo apt install -y -qq build-essential libncurses-dev
      -
        name: Build openssl
        working-directory: ./openssl
        run: |
          ./Configure --prefix=${{ github.workspace }}/lib/openssl
          make
          make install
      -
        name: Build otp
        working-directory: ./otp
        run: |
          ./configure --disable-shared --with-ssl=${{ github.workspace }}/lib/openssl --with-crypto --enable-static-nifs --enable-builtin-zlib
          export RELEASE_ROOT=${{ github.workspace }}/release/${{ github.event.inputs.otp-release-version }}-linux-arm64
          make release
          cd ${{ github.workspace }}/release
          tar czf ${{ github.event.inputs.otp-release-version }}-linux-arm64.tar.gz ${{ github.event.inputs.otp-release-version }}-linux-arm64
      - 
        name: Create the Release
        uses: elgohr/Github-Release-Action@v5
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          title: ${{ github.event.inputs.otp-release-version }}
      -
        name: Upload to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: release/${{ github.event.inputs.otp-release-version }}-linux-arm64.tar.gz
          release_name: ${{ github.event.inputs.otp-release-version }}
          overwrite: true

permissions:
  contents: write
  packages: write
